[package]
name = "indeed"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
weper_lib = { path = "../weper_lib" }
csv_config = { path = "../csv_config" }
tokio = {version="1.36", features=["full"]}
csv = "1.3.0"

